export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REFRESH = 'AUTH_REFRESH';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_CLEAR = 'AUTH_CLEAR';

export const CATAGORY_LOAD_START = 'CATAGORY_LOAD_START';
export const CATAGORY_LOAD_SUCCESS = 'CATAGORY_LOAD_SUCCESS';
export const CATAGORY_LOAD_FAIL = 'CATAGORY_LOAD_FAIL';
export const CATAGORY_RESET = 'CATAGORY_RESET';
export const CATAGORY_TOGGLE = 'CATAGORY_TOGGLE';

export const FILTER_SELECT = 'FILTER_SELECT';

export const COUPON_CLEAR = 'COUPON_CLEAR';

export const COUPON_LOAD_START = 'COUPON_LOAD_START';
export const COUPON_LOAD_SUCCESS = 'COUPON_LOAD_SUCCESS';
export const COUPON_LOAD_FAIL = 'COUPON_LOAD_FAIL';

export const COUPON_ARCHIVED_LOAD_START = 'COUPON_ARCHIVED_LOAD_START';
export const COUPON_ARCHIVED_LOAD_SUCCESS = 'COUPON_ARCHIVED_LOAD_SUCCESS';
export const COUPON_ARCHIVED_LOAD_FAIL = 'COUPON_ARCHIVED_LOAD_FAIL';

export const COUPON_EDIT_START = 'COUPON_EDIT_START';
export const COUPON_EDIT_SUCCESS = 'COUPON_EDIT_SUCCESS';
export const COUPON_EDIT_FAIL = 'COUPON_EDIT_FAIL';

export const COUPON_DELETE_START = 'COUPON_DELETE_START';
export const COUPON_DELETE_SUCCESS = 'COUPON_DELETE_SUCCESS';
export const COUPON_DELETE_FAIL = 'COUPON_DELETE_FAIL';

export const COUPON_CREATE_START = 'COUPON_CREATE_START';
export const COUPON_CREATE_SUCCESS = 'COUPON_CREATE_SUCCESS';
export const COUPON_CREATE_FAIL = 'COUPON_CREATE_FAIL';

export const MY_COUPON_CLEAR = 'MY_COUPON_CLEAR';

export const MY_COUPON_LOAD_START = 'MY_COUPON_LOAD_START';
export const MY_COUPON_LOAD_SUCCESS = 'MY_COUPON_LOAD_SUCCESS';
export const MY_COUPON_LOAD_FAIL = 'MY_COUPON_LOAD_FAIL';

export const MY_COUPON_EDIT_START = 'MY_COUPON_EDIT_START';
export const MY_COUPON_EDIT_SUCCESS = 'MY_COUPON_EDIT_SUCCESS';
export const MY_COUPON_EDIT_FAIL = 'MY_COUPON_EDIT_FAIL';

export const MY_COUPON_DELETE_START = 'MY_COUPON_DELETE_START';
export const MY_COUPON_DELETE_SUCCESS = 'MY_COUPON_DELETE_SUCCESS';
export const MY_COUPON_DELETE_FAIL = 'MY_COUPON_DELETE_FAIL';

export const COMPANIES_CLEAR = 'COMPANIES_CLEAR';

export const COMPANIES_LOAD_START = 'COMPANIES_LOAD_START';
export const COMPANIES_LOAD_SUCCESS = 'COMPANIES_LOAD_SUCCESS';
export const COMPANIES_LOAD_FAIL = 'COMPANIES_LOAD_FAIL';

export const COMPANY_EDIT_START = 'COMPANY_EDIT_START';
export const COMPANY_EDIT_SUCCESS = 'COMPANY_EDIT_SUCCESS';
export const COMPANY_EDIT_FAIL = 'COMPANY_EDIT_FAIL';

export const COMPANY_DELETE_START = 'COMPANY_DELETE_START';
export const COMPANY_DELETE_SUCCESS = 'COMPANY_DELETE_SUCCESS';
export const COMPANY_DELETE_FAIL = 'COMPANY_DELETE_FAIL';

export const INCOME_LOAD_START = 'INCOME_LOAD_START';
export const INCOME_LOAD_SUCCESS = 'INCOME_LOAD_SUCCESS';
export const INCOME_LOAD_FAIL = 'INCOME_LOAD_FAIL';


export const CART_UNLOAD = 'CART_UNLOAD';
export const CART_CLEAR = 'CART_CLEAR';

export const CART_LOAD_START = 'CART_LOAD_START';
export const CART_LOAD_SUCCESS = 'CART_LOAD_SUCCESS';
export const CART_LOAD_FAIL = 'CART_LOAD_FAIL';

export const CART_EMPTY_START = 'CART_EMPTY_START';
export const CART_EMPTY_SUCCESS = 'CART_EMPTY_SUCCESS';
export const CART_EMPTY_FAIL = 'CART_EMPTY_FAIL';

export const CART_REMOVE_ITEM_START = 'CART_REMOVE_ITEM_START';
export const CART_REMOVE_ITEM_SUCCESS = 'CART_REMOVE_ITEM_SUCCESS';
export const CART_REMOVE_ITEM_SUCCESS_FINAL = 'CART_REMOVE_ITEM_SUCCESS_FINAL';
export const CART_REMOVE_ITEM_FAIL = 'CART_REMOVE_ITEM_FAIL';

export const CART_ADD_ITEM_START = 'CART_ADD_ITEM_START';
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS';
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL';
             
export const CART_PURCHASE_ITEM_START = 'CART_PURCHASE_ITEM_START';
export const CART_PURCHASE_ITEM_SUCCESS = 'CART_PURCHASE_ITEM_SUCCESS';
export const CART_PURCHASE_ITEM_FAIL = 'CART_PURCHASE_ITEM_FAIL';

export const CART_PURCHASE_START = 'CART_PURCHASE_START';
export const CART_PURCHASE_SUCCESS = 'CART_PURCHASE_SUCCESS';
export const CART_PURCHASE_FAIL = 'CART_PURCHASE_FAIL';

/// ON PURCHACE
/// FOR EACH ITEM PERFOMR REQUEST AGAINST JERSEY
/// PURCHASE ITEM: -> LOADING = TRUE, PURCHASE=TRUE, ERROR = STRING
/// CHANGE ITEM STATE TO LOADING
/// CHANGE ITME STATE TO PURCHASED
/// CHANGE ITEM STATE TO ERROR


